### ISSUE TITLE
Illegal Token When Changing City

### ISSUE THREAD

**Issue by gr3yfoxhound** [felixhageloh/weather-widget#20]
Changing the city and region, as well as setting automatic location do not select New York. 

Stated as Error, Unexpected Token ILLEGAL

Any Thoughts on how to properly change location?

**Comment by felixhageloh** [comment]
Sounds like an issue that people have when using TextEdit to change the file. Unfortunately, TextEdit replaces the standard double quotes `"` with a slightly different symbol. 
If you are not using TextEdit then make sure that you have quotes around the city name. Hope this helps!

**Comment by gr3yfoxhound** [comment]
Any suggestion of what free product to use?

**Comment by felixhageloh** [comment]
here are a few https://www.elegantthemes.com/blog/resources/the-11-best-code-editors-available-in-2015

The first one, Atom, is free and a few others, like SublimeText, have a few trial that will keep on working indefinitely (but bug you to buy every once in a while)

**Comment by gr3yfoxhound** [comment]
Much appreciated!
