### ISSUE TITLE
Options/Appearance variables not working

### ISSUE THREAD

**Issue by krisvibe** [felixhageloh/weather-widget#21]
Hi -

Noticed that Units and iconSet no longer work.  Changed units to 'f' and iconSet to 'yahoo' and no update was applied.

**Comment by felixhageloh** [comment]
Hi, thanks for reporting. Can you try to restart Übersicht and see if the issue persists? I tried it quickly and it seems to work fine for me, so it sounds like the file watching might be broken for you temporarily. A restart should fix that

**Comment by krisvibe** [comment]
I closed out of Übersicht completely and now it doesn't appear at all.  I see an Unexpected Token ILLEGAL error message in OSX Notifications - is there a way to debug?

**Comment by felixhageloh** [comment]
you can open the debug console from the Übersicht menu, that should give you more information. But basically what this means is that there is some syntax error inside the widget

**Comment by Neto** [comment]
I'm getting an error "bash: line 1 <path>: No such file or directory

**Comment by jmcguire** [comment]
@krisvibe and @Neto , can you attach your index.coffee file here?

**Comment by rwong8** [comment]
I'm getting the same error message. i made only 1 change from 'c' to 'f'.
[index.txt](https://github.com/felixhageloh/weather-widget/files/93466/index.txt)

**Comment by jmcguire** [comment]
@rwong8, there's a hard-to-spot bug in your file. The **f** is surrounded by curly quotes instead of straight quotes. **‘f’** v. **'f'**

But when I fixed that, the widget worked fine on my computer.

**Comment by rwong8** [comment]
Thanks, I'll give that a try, but wanted to let u know, that I downloaded straight from the übersicht widget siteband changed the c to a f without changing the " ' ". So you might want to check the file that was uploaded originally with the widget.

**Comment by krisvibe** [comment]
Great catch - that was the issue.  TextEdit wants to change the straight quotes to curly every time you edit a parameter.  Even if you edit within the quotes, it converts them to curly.  After a few edits I'm back up and running.

Thanks again!
