### ISSUE TITLE
Weather widget acts randomly

### ISSUE THREAD

**Issue by nanobra1n** [felixhageloh/weather-widget#22]
For about a week now the weather widget stopped working. The weather forecast starts at a random days of the week every time the widget gets updated and the current condition fluctuate on every update as well. Looking at the output of the get-weather script it seems like data pulled changes every time it is pulled and is stale by varying amounts (but at least 10 days). My location is static (Severn, MD).

**Comment by AndyG1128** [comment]
I saw a similar effect.  When I switched the icon set back to original, it seems to have started working correctly.  Not sure what that means as I am just learning coffee scripting, but it is a starting point

**Comment by felixhageloh** [comment]
thanks for reporting - I will see if I can reproduce. Are there any errors in the console?

**Comment by nanobra1n** [comment]
No errors on the console and for the last couple of days everything works as designed. I think we can chalk it up to problems on the Yahoo backend. If I knew more about coffee scripting I would adapt it to forecast.io :)
