### ISSUE TITLE
Rotating City Location 

### ISSUE THREAD

**Issue by prestoncampbell** [felixhageloh/weather-widget#26]
Hello, I saw that there was the dynamic city location option, but I was wondering if it would be possible to have multiple locations, where the data would change every 30 seconds or so. I am not looking to switch between dynamic and static, just a few different static locations.

**Comment by felixhageloh** [comment]
at the moment it is not possible without writing some code. If it is something you want to take on I can give you some pointers!

**Comment by prestoncampbell** [comment]
Hey man, I totally would, but honestly I barely was able to install ubersicht. If its somewhat easy I could give it a shot, but I don't really know how to do much coding.

**Comment by felixhageloh** [comment]
Alright, I see! I'm afraid I also don't have simple instructions on how to do that at the moment - it will require some looking into. 
The best suggestion I can offer for now is to have several widgets with a different city each, but of course that's not exactly what you are looking for.
