### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by RazzaFrazzle** [felixhageloh/weather-widget#34]
<img width="360" alt="screen shot 2016-08-25 at 11 10 48 am" src="https://cloud.githubusercontent.com/assets/21244234/17974787/6da3988a-6ab5-11e6-8ecb-12f8f6aecd02.png">

All I did was drop the folder into my uebersicht and it gave me this. After I edited default location and font in case that matters

**Comment by felixhageloh** [comment]
does this problem persist when you restart Übersicht?

**Comment by RazzaFrazzle** [comment]
Yeah, it does

**Comment by felixhageloh** [comment]
sorry I didn't see your comment about editing the location and font. My best guess then is that you have a syntax error somewhere. Are you using TextEdit to change the file by any chance?

**Comment by RazzaFrazzle** [comment]
Yes, I am xD

**Comment by RazzaFrazzle** [comment]
Hmm.. When I unistalled it and installed it again, I got the same error, so I didn't make a mistake in the index.coffee

**Comment by felixhageloh** [comment]
can you post your index.coffee file here? The problem with TextEdit is that it replace regular quotes `"` with 'fancy' ones `”`. So you need to disable 'Smart Quotes' if you want to use it for code editing
<img width="400" alt="screen shot 2016-09-02 at 14 53 35" src="https://cloud.githubusercontent.com/assets/367503/18204436/1a661e54-711d-11e6-8107-6ca6fe9760d8.png">

**Comment by RazzaFrazzle** [comment]
Oh.... Well that may explain a lot of previous textedit failures xD thanks. Unfortunately, I still got the same message even when I uninstalled and reinstalled the widget. Its not a big deal if you don't know what the problem is... I mean, I have no idea what any of the error means so..

**Comment by RazzaFrazzle** [comment]
OMG I GOT IT

**Comment by RazzaFrazzle** [comment]
I HAD THE FULL -MASTER FILE IN WHEN I WAS SUPPOSED TO JUST HAVE WEATHER.WIDGET

**Comment by RazzaFrazzle** [comment]
Sorry for all the trouble... so stupid lol

**Comment by felixhageloh** [comment]
No worries - glad you figured it out :)
