### ISSUE TITLE
Portugal not supported

### ISSUE THREAD

**Issue by premedios** [felixhageloh/weather-widget#35]
Waht do I put as the city and region to get weather details for Oeiras in Portugal? I tried putting region as 'Portugal' and city as 'Oeiras', put it displays the error message 'Could not retrieve weather data for Oeiras, 11' I also tried putting region as 'Portugal' and city as 'Oeiras' and got the same message.

**Comment by felixhageloh** [comment]
I think the region should be `PT` in this case. What I usually do is to go to Yahoo's whether site https://www.yahoo.com/news/weather and search for the city there. You can then see what region code they use

**Comment by felixhageloh** [comment]
hope this helps  - feel free to reopen if you still have issues
