### ISSUE TITLE
High cpu use

### ISSUE THREAD

**Issue by kokoko3k** [felixhageloh/weather-widget#39]
On my laptop, when there is no internet connection and the widgets show the spinning animation, the cpu use is very high (it reaches even 40% - i3-3110M CPU @ 2.40GHz).
Maybe is plasma fault, maybe is qt fault, i don't know, but whould it be possible to insert a preference to disable the spinning animation and just show "refreshing..."?
Thanks and keep up the good work!

**Comment by felixhageloh** [comment]
hey, sorry for the late response. Which widget is it and do you know whether it is doing other things in the meantime (maybe trying re-connected very rapidly)?

**Comment by kokoko3k** [comment]
Hi,
The widget i'm talking about is the "desktop" one.
I don't think the cpu use is due to several connections made in short time, as i can see in the logs that it does a connection every several seconds.
Thank you for looking into this.

**Comment by felixhageloh** [comment]
is it this one your are talking about http://tracesof.net/uebersicht-widgets/#Evangelion or the desktop background one http://tracesof.net/uebersicht-widgets/#backgroundwidget?

**Comment by kokoko3k** [comment]
Oh my, i'm so sorry!
It is not your widget, but this one:
https://github.com/librehat/com.librehat.yahooweather
Different os, different widget, i apologize :)

**Comment by felixhageloh** [comment]
😆 np!
