### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Neto** [felixhageloh/weather-widget#42]
Hi Felix!
Greetings from Brazil!
I'm writing to ask for get your help
I tried to alter the code myself, but couldn't
Is it to hard to add an option to set the colors of the original icons?
I mean...a color for each condition?
Any tip would help a lot!

**Comment by felixhageloh** [comment]
Hi! You could probably define a color mapping, like the icon mapping at the bottom of the widget code. You can then set the color using css at the place were the code calls `@getIcon`

I hope this helps a bit!

**Comment by Neto** [comment]
Thanks!
Not sure I have the skills ;) but will try!

cheers

n

**Comment by felixhageloh** [comment]
Good luck and feel free to follow up here! (closing the issue for now)
