### ISSUE TITLE
Celsius doesn't work

### ISSUE THREAD

**Issue by jekylgithub** [felixhageloh/weather-widget#43]
Made many changes including opacity: 0.7 change and font sizes of various components to suit desktop, love it, then, as a UK resident, I changed to celsius from fahrenheit, and the widget simply won't display. No error message from ubersicht, but it just disappears. Changing back to fahrenheit in the script does;t make it reappear either. Deleted and reinstalled widget afresh, then just changed the units before any other mod, same thing, needs delete and reinstall again. Shame as I really much prefer celsius to fahrenheit

**Comment by felixhageloh** [comment]
which text editor are you using to make the changes? It sounds like a common issue with TextEdit: it automatically changes regular quotes into 'curly quotes' on save. You can turn this off in Preferences (Options section) -> Smart Quotes, or alternatively, use a different text editor.

**Comment by jekylgithub** [comment]
Aha, v interesting  to know, Text Edit indeed. Had no idea, will give that a try. When i reopened things to check and try repeatedly, it did seem to have kept the ‘quotes’ I used instead of changing but will look. 

Thanks so much for the reply

J

**Comment by felixhageloh** [comment]
👍 glad I could help. The change is very subtle:

" vs “

and

' vs ‘
